from . import (
    auth as auth_router,
    tenants as tenants_router,
    users as users_router,
    stores as stores_router,
    warehouses as warehouses_router,
    modules as modules_router,
    products as products_router,
    inventory as inventory_router,
    requisitions as requisitions_router,
    transfers as transfers_router,
    invoices as invoices_router,
    suppliers as suppliers_router,
    sales as sales_router,
    dashboard as dashboard_router,
    reports as reports_router,
    audit as audit_router,
    notifications as notifications_router,
    seed as seed_router,
)

ALL_ROUTERS = [
    auth_router.router,
    tenants_router.router,
    users_router.router,
    stores_router.router,
    warehouses_router.router,
    modules_router.router,
    products_router.router,
    inventory_router.router,
    requisitions_router.router,
    transfers_router.router,
    invoices_router.router,
    suppliers_router.router,
    sales_router.router,
    dashboard_router.router,
    reports_router.router,
    audit_router.router,
    notifications_router.router,
    seed_router.router,
]
